// Auto-generated by convert.py — do not edit by hand.
// Sources: tracker.md (Tiers A-I) and answers.md (FILLKIT).
const SCHOLARSHIPS = [
  {"id": "A01", "name": "Sallie $2,000 No Essay", "tier": "A", "amount": "$2,000", "deadline": {"raw": "Sep 30, 2026 (monthly)", "recurring": true, "fuzzy": false}, "effort": "2-min form", "status": "todo", "recurring": true, "url": "https://sallie.com/scholarships/no-essay", "notes": "16+, HS jr/sr planning college; funds paid to school", "kind": ""},
  {"id": "A02", "name": "Niche $2,000 No Essay", "tier": "A", "amount": "$2,000", "deadline": {"raw": "monthly", "recurring": true, "fuzzy": true}, "effort": "account, 1 entry", "status": "todo", "recurring": true, "url": "https://niche.com/colleges/scholarships/no-essay-scholarship/", "notes": "US citizen or visa", "kind": ""},
  {"id": "A03", "name": "SoFi $2,500 Giveaway", "tier": "A", "amount": "$2,500", "deadline": {"raw": "Sep 30, 2026", "recurring": false, "fuzzy": false}, "effort": "form", "status": "todo", "recurring": true, "url": "https://refer.sofi.com/c/2077228/3283756/11190", "notes": "18+ only", "kind": ""},
  {"id": "A04", "name": "Appily Easy Money", "tier": "A", "amount": "$1,000", "deadline": {"raw": "monthly", "recurring": true, "fuzzy": true}, "effort": "account + profile", "status": "todo", "recurring": true, "url": "https://appily.com/scholarships/easy-money-scholarship", "notes": "13+; data-broker privacy flag", "kind": ""},
  {"id": "A05", "name": "ScholarshipOwl $2,026", "tier": "A", "amount": "$2,026", "deadline": {"raw": "monthly", "recurring": true, "fuzzy": true}, "effort": "sign-in", "status": "todo", "recurring": true, "url": "https://scholarshipowl.com", "notes": "freemium, data-heavy", "kind": ""},
  {"id": "A06", "name": "ScholarshipOwl $50k program", "tier": "A", "amount": "$1,000 ×4/mo", "deadline": {"raw": "monthly", "recurring": true, "fuzzy": true}, "effort": "sign-up", "status": "todo", "recurring": true, "url": "https://scholarshipowl.com", "notes": "realistic win = $1k", "kind": ""},
  {"id": "A07", "name": "Bold.org point tiers", "tier": "A", "amount": "$1k–$10k", "deadline": {"raw": "Sep 30, 2026", "recurring": false, "fuzzy": false}, "effort": "1 profile, minutes", "status": "todo", "recurring": true, "url": "https://bold.org/scholarships/by-type/no-essay-scholarships/", "notes": "~90 no-essay awards on one profile", "kind": ""},
  {"id": "A08", "name": "Scholly Easy Apply (Sallie)", "tier": "A", "amount": "up to $13k (18 awards)", "deadline": {"raw": "Sep 30, 2026", "recurring": false, "fuzzy": false}, "effort": "1 form ~2 min", "status": "todo", "recurring": true, "url": "https://sallie.com/scholarships/scholly/easy-apply", "notes": "bundles 18 scholarships", "kind": ""},
  {"id": "A09", "name": "Lenny.ai sweepstakes", "tier": "A", "amount": "$1,001 / $2,999", "deadline": {"raw": "Sep 28–29, 2026", "recurring": false, "fuzzy": true}, "effort": "quick form", "status": "todo", "recurring": false, "url": "https://lenny.ai/lenny-scholarship", "notes": "newer sponsor — verify amounts/rules", "kind": ""},
  {"id": "A10", "name": "Citizens / College Raptor Sweepstakes", "tier": "A", "amount": "$2,500", "deadline": {"raw": "quarterly", "recurring": false, "fuzzy": true}, "effort": "web form", "status": "todo", "recurring": true, "url": "https://citizensbank.com/student-loans/scholarship.aspx", "notes": "HS senior, AR eligible; re-enter quarterly", "kind": ""},
  {"id": "A11", "name": "Abe's \"Plain, Honest\" Scholarship", "tier": "A", "amount": "$1,500", "deadline": {"raw": "monthly", "recurring": true, "fuzzy": true}, "effort": "trivial form", "status": "todo", "recurring": true, "url": "https://abestudentloans.com", "notes": "undergrad; no purchase/loan needed", "kind": ""},
  {"id": "A12", "name": "College Ave $1,000 Monthly Sweepstakes", "tier": "A", "amount": "$1,000", "deadline": {"raw": "monthly", "recurring": true, "fuzzy": true}, "effort": "form", "status": "todo", "recurring": true, "url": "https://collegeave.com/promotions/", "notes": "students & parents; one entry/mo", "kind": ""},
  {"id": "A13", "name": "Edvisors Monthly Scholarship", "tier": "A", "amount": "$1,000", "deadline": {"raw": "monthly", "recurring": true, "fuzzy": true}, "effort": "form", "status": "todo", "recurring": true, "url": "https://edvisors.com/rules-1k-scholarship/", "notes": "HS senior 16+; privacy flag — bonus entries share emails", "kind": ""},
  {"id": "A14", "name": "Discover No-Essay Sweepstakes", "tier": "A", "amount": "$5,000", "deadline": {"raw": "monthly", "recurring": true, "fuzzy": true}, "effort": "form", "status": "todo", "recurring": true, "url": "https://discover.com", "notes": "18+ only", "kind": ""},
  {"id": "B01", "name": "BigFuture (College Board)", "tier": "B", "amount": "$40k + $500 monthly", "deadline": {"raw": "monthly drawings", "recurring": true, "fuzzy": true}, "effort": "free planning steps", "status": "todo", "recurring": false, "url": "https://bigfuture.collegeboard.org/pay-for-college/bigfuture-scholarships/scholarship-details", "notes": "do all 6 steps; more = more entries; higher chance if low-income", "kind": ""},
  {"id": "B02", "name": "Niche $40,000 No Essay", "tier": "B", "amount": "$40,000", "deadline": {"raw": "Oct 15, 2026", "recurring": false, "fuzzy": false}, "effort": "5 min", "status": "todo", "recurring": false, "url": "https://niche.com/colleges/scholarships/40k-no-essay-scholarship-2026/", "notes": "winner by Nov 15, 2026", "kind": ""},
  {"id": "B03", "name": "Bold.org Be Bold $25k", "tier": "B", "amount": "$25,000", "deadline": {"raw": "Sep 30, 2026", "recurring": false, "fuzzy": false}, "effort": "profile, no essay", "status": "todo", "recurring": false, "url": "https://bold.org/scholarships/the-be-bold-no-essay-scholarship/", "notes": "6-yr track record, $160k paid", "kind": ""},
  {"id": "B04", "name": "US Bank Student Scholarship", "tier": "B", "amount": "$2.5k–$20k tiered", "deadline": {"raw": "Oct 30, 2026", "recurring": false, "fuzzy": false}, "effort": "financial-ed lessons", "status": "todo", "recurring": false, "url": "https://scholarships360.org/scholarships/search/us-bank-student-scholarship/", "notes": "17+; more modules = higher tier", "kind": ""},
  {"id": "B05", "name": "Scholarships360 $10k", "tier": "B", "amount": "$10,000", "deadline": {"raw": "monthly; final Jun 30, 2027", "recurring": true, "fuzzy": false}, "effort": "account", "status": "todo", "recurring": false, "url": "https://scholarships360.org/scholarships/search/10000-no-essay-scholarship/", "notes": "site is scholarships360.org", "kind": ""},
  {"id": "B06", "name": "Ascent $10k Summer Giveaway", "tier": "B", "amount": "$10,000", "deadline": {"raw": "Sep 30, 2026", "recurring": false, "fuzzy": false}, "effort": "quick form", "status": "todo", "recurring": false, "url": "https://ascentfunding.com/scholarships/summer-scholarship-giveaway-10k", "notes": "lender-sponsored — read official rules", "kind": ""},
  {"id": "B07", "name": "Coca-Cola Scholars", "tier": "B", "amount": "$20,000 (150 awards)", "deadline": {"raw": "Sep 30, 2026, 5pm ET — phase 1 OPEN now", "recurring": false, "fuzzy": false}, "effort": "phase 1: no essays/transcripts/recs", "status": "todo", "recurring": false, "url": "https://coca-colascholarsfoundation.org/apply/", "notes": "leadership + service focus — Max's profile fits; later phases add essays", "kind": ""},
  {"id": "B08", "name": "Doodle for Google", "tier": "B", "amount": "up to $55k", "deadline": {"raw": "annual (~Oct) — verify cycle", "recurring": false, "fuzzy": true}, "effort": "draw + form", "status": "todo", "recurring": false, "url": "https://doodles.google.com/d4g/", "notes": "official page unreachable at research time", "kind": ""},
  {"id": "B09", "name": "Christian Connector / Catholic / Protestant", "tier": "B", "amount": "$5k / $2k / $2k", "deadline": {"raw": "May 31, 2027", "recurring": false, "fuzzy": false}, "effort": "simple form", "status": "todo", "recurring": false, "url": "https://christianconnector.com", "notes": "only if attending a faith-based college", "kind": ""},
  {"id": "C01", "name": "Unigo $10k", "tier": "C", "amount": "$10,000", "deadline": {"raw": "Dec 31, 2026", "recurring": false, "fuzzy": false}, "effort": "250 words", "status": "todo", "recurring": false, "url": "https://unigo.com/scholarships/our-scholarships/unigo-10k-scholarship", "notes": "\"smart, funny or rich?\"; privacy flag (sells info)", "kind": ""},
  {"id": "C02", "name": "10 Words or Less", "tier": "C", "amount": "$1,500", "deadline": {"raw": "Nov 15, 2026", "recurring": false, "fuzzy": false}, "effort": "≤10 words", "status": "todo", "recurring": false, "url": "https://studentscholarships.org/scholarship/10258/10-words-or-less-scholarship", "notes": "ages 17–25, US/Canada college Fall 2027", "kind": ""},
  {"id": "C03", "name": "Raise.me micro-scholarships", "tier": "C", "amount": "hundreds→tens of thousands", "deadline": {"raw": "ongoing", "recurring": true, "fuzzy": true}, "effort": "portfolio of achievements", "status": "todo", "recurring": false, "url": "https://raise.me", "notes": "no essays; partner colleges", "kind": ""},
  {"id": "D01", "name": "Academic Challenge", "tier": "D", "amount": "$2,000 (yr 1)", "deadline": {"raw": "in SAMS", "recurring": false, "fuzzy": true}, "effort": "SAMS + FAFSA", "status": "todo", "recurring": false, "url": "https://sams.adhe.edu", "notes": "lottery-funded; Diploma of Merit or GPA basis", "kind": ""},
  {"id": "D02", "name": "Governor's Scholars (renamed from GDS)", "tier": "D", "amount": "up to $5,000/yr", "deadline": {"raw": "in SAMS", "recurring": false, "fuzzy": true}, "effort": "SAMS + FAFSA", "status": "todo", "recurring": false, "url": "https://sams.adhe.edu", "notes": "associate-degree or Diploma of Distinction paths", "kind": ""},
  {"id": "D03", "name": "ACCESS to Acceleration", "tier": "D", "amount": "$65/hr, max $2,000/yr", "deadline": {"raw": "in SAMS", "recurring": false, "fuzzy": true}, "effort": "SAMS", "status": "todo", "recurring": false, "url": "https://sams.adhe.edu", "notes": "replaces Concurrent Challenge (repealed); dual-enrollment", "kind": ""},
  {"id": "D04", "name": "Arkansas Future Grant", "tier": "D", "amount": "2-yr tuition or $3,800 (4-yr)", "deadline": {"raw": "in SAMS", "recurring": false, "fuzzy": true}, "effort": "SAMS + FAFSA", "status": "todo", "recurring": false, "url": "https://sams.adhe.edu", "notes": "workforce/certificate/AA", "kind": ""},
  {"id": "D05", "name": "Workforce Challenge", "tier": "D", "amount": "$3,000/yr", "deadline": {"raw": "in SAMS", "recurring": false, "fuzzy": true}, "effort": "app", "status": "todo", "recurring": false, "url": "https://sams.adhe.edu", "notes": "5 fields: mfg, health, IT, construction, logistics", "kind": ""},
  {"id": "D06", "name": "Teacher Academy", "tier": "D", "amount": "up to $12,000/yr", "deadline": {"raw": "Fall 2026 window", "recurring": false, "fuzzy": true}, "effort": "app", "status": "todo", "recurring": false, "url": "https://sams.adhe.edu", "notes": "only if planning to teach", "kind": ""},
  {"id": "D07", "name": "Heroes Scholarship", "tier": "D", "amount": "tuition + housing + fees", "deadline": {"raw": "2026 cycle", "recurring": false, "fuzzy": true}, "effort": "app", "status": "todo", "recurring": false, "url": "https://sams.adhe.edu", "notes": "⚠️ dad is active-duty (deployed Germany) — Heroes likely N/A unless he has a qualifying status (Medal of Honor / Purple Heart / disabled vet / DoD medical retiree); confirm with dad", "kind": ""},
  {"id": "E01", "name": "UA freshman scholarship app (ONE app → all awards)", "tier": "E", "amount": "Chancellor's up to $10k/yr · Silas Hunt $5–8k/yr · Advance AR $4k/yr · Honors Academy $4k/yr · Razorback Bridge $3.5k/yr · one-time $1k–$5k", "deadline": {"raw": "Admit: Nov 1, 2026 (pri) / Jan 15, 2027 · Scholarship: Nov 15, 2026 (pri) / Feb 1, 2027", "recurring": false, "fuzzy": false}, "effort": "short form + 3 works + prompts", "status": "todo", "recurring": false, "url": "https://scholarships.uark.edu/guide-to-academic-freshman-scholarships/", "notes": "Max's #1 priority app. UA recalcs GPA (weighted) + superscores ACT — retake to unlock higher tiers", "kind": ""},
  {"id": "E02", "name": "Chancellor's Merit", "tier": "E", "amount": "$12,000/yr", "deadline": {"raw": "via National Merit", "recurring": false, "fuzzy": true}, "effort": "none beyond NM", "status": "todo", "recurring": false, "url": "https://scholarships.uark.edu", "notes": "needs National Merit + UA #1", "kind": ""},
  {"id": "E03", "name": "Honors College Fellowship", "tier": "E", "amount": "up to $80k over 4 yrs", "deadline": {"raw": "Nov 15, 2026 / Feb 1, 2027", "recurring": false, "fuzzy": false}, "effort": "600-word essay + recs", "status": "todo", "recurring": false, "url": "https://honors.uark.edu/find-funding/index.php", "notes": "⚠️ needs ACT 32 + 3.90 weighted — Max at 21/3.85; revisit only if ACT improves", "kind": ""},
  {"id": "E04", "name": "Fostering Success", "tier": "E", "amount": "up to $9,000/yr ×4", "deadline": {"raw": "Jan 15 / Feb 1, 2027", "recurring": false, "fuzzy": false}, "effort": "UA app + FAFSA", "status": "todo", "recurring": false, "url": "https://scholarships.uark.edu", "notes": "only if AR foster care ≥1 yr", "kind": ""},
  {"id": "F01", "name": "NWACC Foundation", "tier": "F", "amount": "$350k+ pool, 350+ students", "deadline": {"raw": "rolling / per fund", "recurring": true, "fuzzy": true}, "effort": "one app", "status": "todo", "recurring": false, "url": "https://nwaccfoundation.org/how-to-apply", "notes": "community college route; transfer path to UA", "kind": ""},
  {"id": "F02", "name": "Arkansas Community Foundation", "tier": "F", "amount": "dozens of endowments (varies)", "deadline": {"raw": "portal opens Feb 1, 2027", "recurring": false, "fuzzy": false}, "effort": "eligibility quiz + app", "status": "todo", "recurring": false, "url": "https://arcf.org/apply/scholarships/", "notes": "some funds are county/HS/college-specific (Benton Co. exists)", "kind": ""},
  {"id": "F03", "name": "SPSF NWA (single parents)", "tier": "F", "amount": "$1,250–$2,500/term", "deadline": {"raw": "Fall Jun 15 · Spr Oct 15 · Sum Mar 15", "recurring": false, "fuzzy": true}, "effort": "app + interview", "status": "todo", "recurring": false, "url": "https://spsfnwa.org/scholarships/", "notes": "⚠️ single-parent household ✅ but income >$100k likely fails \"low-moderate income\" — confirm before interview", "kind": ""},
  {"id": "F04", "name": "Rogers Rotary Club", "tier": "F", "amount": "varies", "deadline": {"raw": "ask club", "recurring": false, "fuzzy": true}, "effort": "call/email", "status": "todo", "recurring": false, "url": "https://rogersrotary.org", "notes": "not published online — contact directly", "kind": ""},
  {"id": "F05", "name": "Rogers ISD / counselors", "tier": "F", "amount": "district list", "deadline": {"raw": "ask", "recurring": false, "fuzzy": true}, "effort": "ask counselors", "status": "todo", "recurring": false, "url": "", "notes": "district doesn't publish a list", "kind": ""},
  {"id": "F06", "name": "Rogers Public Schools Community-Based Scholarship", "tier": "F", "amount": "$100–$40,000 (many donors)", "deadline": {"raw": "Jan 1–31, 2027", "recurring": false, "fuzzy": true}, "effort": "SmarterSelect app", "status": "todo", "recurring": false, "url": "https://rogersscholarships.com", "notes": "Rogers senior; notify HS Scholarship Coordinator", "kind": ""},
  {"id": "F07", "name": "Arkansas Federal Credit Union Scholarship", "tier": "F", "amount": "$5,000", "deadline": {"raw": "~Jan–Mar 2027", "recurring": false, "fuzzy": true}, "effort": "essay + 2 recs", "status": "todo", "recurring": false, "url": "https://afcu.org", "notes": "AFCU member or child of member", "kind": ""},
  {"id": "F08", "name": "NWA Young Professionals Scholarship", "tier": "F", "amount": "$500–$2,000", "deadline": {"raw": "spring 2027", "recurring": false, "fuzzy": true}, "effort": "app", "status": "todo", "recurring": false, "url": "https://nwayp.org", "notes": "Benton/Washington Co senior → Arkansas college", "kind": ""},
  {"id": "F09", "name": "Walmart \"Live Better U\"", "tier": "F", "amount": "100% tuition + books (bachelor's; expanded to skilled trades 2025)", "deadline": {"raw": "HR-enrolled — mom checks benefits portal", "recurring": false, "fuzzy": true}, "effort": "N/A", "status": "skipped", "recurring": false, "url": "https://walmart.com/careers/", "notes": "✅ parent at Walmart/Sam's Club confirmed — potentially covers ALL UA tuition. Have mom verify current caps via benefits — does not apply", "kind": "benefit"},
  {"id": "G01", "name": "QuestBridge National College Match", "tier": "G", "amount": "~$200k (full ride)", "deadline": {"raw": "Aug–Oct 2026", "recurring": false, "fuzzy": true}, "effort": "essays + recs + transcript", "status": "todo", "recurring": false, "url": "https://questbridge.org", "notes": "⚠️ income >$100k likely disqualified — verify 2026 income guidelines before investing essay time", "kind": ""},
  {"id": "G02", "name": "Jack Kent Cooke", "tier": "G", "amount": "$40k+/yr × up to 4", "deadline": {"raw": "opens Nov 2026", "recurring": false, "fuzzy": true}, "effort": "short form + FAFSA need", "status": "todo", "recurring": false, "url": "https://jackkentcooke.org", "notes": "⚠️ income >$100k likely disqualified; apply only if user insists", "kind": ""},
  {"id": "G03", "name": "Elks Most Valuable Student", "tier": "G", "amount": "$30k top + lodge/district", "deadline": {"raw": "lodge early 2027; natl Mar–Apr 2027", "recurring": false, "fuzzy": true}, "effort": "2 essays + recs + leadership", "status": "todo", "recurring": false, "url": "https://elks.org", "notes": "check local lodge in Rogers/Bentonville", "kind": ""},
  {"id": "G04", "name": "Horatio Alger", "tier": "G", "amount": "$25,000", "deadline": {"raw": "Jan–Feb 2027", "recurring": false, "fuzzy": true}, "effort": "essays + need + recs", "status": "todo", "recurring": false, "url": "https://alger.org", "notes": "⚠️ income >$100k likely disqualified; apply only if user insists", "kind": ""},
  {"id": "G05", "name": "National Merit Scholarship", "tier": "G", "amount": "$2,500 + corporate; → UA Chancellor's Merit $12k/yr", "deadline": {"raw": "ACT Oct–Dec 2026 (senior route)", "recurring": false, "fuzzy": true}, "effort": "test only", "status": "skipped", "recurring": false, "url": "https://nationalmerit.org", "notes": "⚠️ needs ~top 1% index (≈ACT 33+) — ACT 21 not competitive; skip", "kind": ""},
  {"id": "G06", "name": "Arkansas Alumni Association (UA-bound)", "tier": "G", "amount": "unknown", "deadline": {"raw": "unknown", "recurring": false, "fuzzy": true}, "effort": "—", "status": "todo", "recurring": false, "url": "https://arkansasalumni.org", "notes": "behind login wall — verify with UA", "kind": ""},
  {"id": "G07", "name": "National Cyber Scholarship Foundation", "tier": "G", "amount": "$2,500–$3,500 + free SANS training", "deadline": {"raw": "CyberStart opens ~Fall 2026; apps ~Jan 2027", "recurring": false, "fuzzy": true}, "effort": "CTF-style competition", "status": "todo", "recurring": false, "url": "https://nationalcyberscholarship.org", "notes": "pure merit, no income cap; cybersecurity cert helps", "kind": ""},
  {"id": "G08", "name": "NFIB Young Entrepreneur Award", "tier": "G", "amount": "$1,000–$15,000", "deadline": {"raw": "opens ~Oct 1, 2026; ~Dec 18, 2026", "recurring": false, "fuzzy": true}, "effort": "essay + phone interview", "status": "todo", "recurring": false, "url": "https://nfib.com", "notes": "HS senior who owns a business (Max Mows fits); no income cap", "kind": ""},
  {"id": "G09", "name": "Amazon Future Engineer Scholarship", "tier": "G", "amount": "$40,000 ($10k/yr ×4) + internship", "deadline": {"raw": "~Jan 15, 2027", "recurring": false, "fuzzy": true}, "effort": "app", "status": "conditional", "recurring": false, "url": "https://amazonfutureengineer.com/scholarships", "notes": "CS major; need-gated — long shot at >$100k", "kind": ""},
  {"id": "G10", "name": "Generation Google (North America)", "tier": "G", "amount": "$10,000", "deadline": {"raw": "~Aug (annual)", "recurring": false, "fuzzy": true}, "effort": "app", "status": "conditional", "recurring": false, "url": "https://edu.google.com", "notes": "CS; need + DEI selection; Hispanic heritage helps", "kind": ""},
  {"id": "G11", "name": "Lockheed Martin STEM Scholarship", "tier": "G", "amount": "~$10,000/yr", "deadline": {"raw": "~Mar–Apr", "recurring": false, "fuzzy": true}, "effort": "app", "status": "conditional", "recurring": false, "url": "https://lockheedmartin.com", "notes": "eng/CS; need + underrepresented gate; verify 2027 cycle (possible pause)", "kind": ""},
  {"id": "G12", "name": "(ISC)² Undergraduate Cybersecurity Scholarship", "tier": "G", "amount": "$1,000–$5,000", "deadline": {"raw": "~Mar 15", "recurring": false, "fuzzy": true}, "effort": "essays + 1 rec", "status": "conditional", "recurring": false, "url": "https://iamcybersafe.org/s/academic-scholarships", "notes": "cybersecurity degree; need-weighted selection", "kind": ""},
  {"id": "G13", "name": "CyberPatriot (AFA) National Youth Cyber Defense", "tier": "G", "amount": "sponsor scholarships (varies)", "deadline": {"raw": "Oct 2026 – Mar 2027", "recurring": false, "fuzzy": true}, "effort": "team competition", "status": "conditional", "recurring": false, "url": "https://uscyberpatriot.org", "notes": "competition-based; many prizes tied to partner schools", "kind": ""},
  {"id": "G14", "name": "DECA Inc. scholarships", "tier": "G", "amount": "$1,000–$2,500", "deadline": {"raw": "~Jan 11, 2027", "recurring": false, "fuzzy": true}, "effort": "transcript + 3 recs", "status": "conditional", "recurring": false, "url": "https://deca.org/scholarships", "notes": "requires DECA membership", "kind": ""},
  {"id": "G15", "name": "FBLA scholarships", "tier": "G", "amount": "$500–$2,000", "deadline": {"raw": "~Apr 15", "recurring": false, "fuzzy": true}, "effort": "app", "status": "conditional", "recurring": false, "url": "https://fbla.org", "notes": "requires FBLA membership", "kind": ""},
  {"id": "G16", "name": "Ramsey Education Scholarship", "tier": "G", "amount": "$1,000 ×5", "deadline": {"raw": "~May 31, 2027", "recurring": false, "fuzzy": true}, "effort": "essay or video", "status": "conditional", "recurring": false, "url": "https://ramseysolutions.com", "notes": "requires Ramsey Foundations course (~$30)", "kind": ""},
  {"id": "G17", "name": "NFTE World Series of Innovation", "tier": "G", "amount": "$1,500 / $600 / $300", "deadline": {"raw": "Dec 12, 2026", "recurring": false, "fuzzy": false}, "effort": "free competition", "status": "conditional", "recurring": false, "url": "https://nfte.com", "notes": "grades 9–12; on-ramp to NFTE funds", "kind": ""},
  {"id": "H01", "name": "HSF Scholar Program (Hispanic Scholarship Fund)", "tier": "H", "amount": "$500–$5,000", "deadline": {"raw": "~Jan–Feb 2027 (2027 cycle; confirm on site)", "recurring": false, "fuzzy": true}, "effort": "short app + essay + FAFSA", "status": "todo", "recurring": false, "url": "https://hsf.net/scholarship", "notes": "Best-fit heritage pick. No income cap; US citizen/PR/DACA; GPA 3.0+; identify as Hispanic heritage; awards >$30M/yr", "kind": ""},
  {"id": "H02", "name": "LULAC National Scholarship Fund (LNSF)", "tier": "H", "amount": "$250–$2,000", "deadline": {"raw": "~early 2027, closes ~May 2027 (confirm)", "recurring": false, "fuzzy": true}, "effort": "short app + essay", "status": "todo", "recurring": false, "url": "https://lnesc.org/scholarships/lulac/", "notes": "No income cap; DACA/PR/citizen; ✅ Max is VP of a LULAC Youth Council — local council participation likely satisfied; confirm council is LNSF-participating", "kind": ""},
  {"id": "H03", "name": "Prospanica", "tier": "H", "amount": "up to $5,000", "deadline": {"raw": "~Feb–May 2027 (confirm)", "recurring": false, "fuzzy": true}, "effort": "membership + app + essay", "status": "todo", "recurring": false, "url": "https://prospanica.org/scholarships/", "notes": "Membership fee (hardship waiver avail); ⚠️ may require already-enrolled college freshman at app time — email scholarships@prospanica.org", "kind": ""},
  {"id": "H04", "name": "USHLI Dr. Juan Andrade Jr. Scholarship", "tier": "H", "amount": "$1,000", "deadline": {"raw": "reopens ~Fall 2026 (Dec)", "recurring": false, "fuzzy": true}, "effort": "2 essays + 2 recs + résumé + transcript", "status": "todo", "recurring": false, "url": "https://ushli.org/dr-juan-andrade-jr-scholarship-for-young-hispanic-leaders/", "notes": "Non-citizens eligible; age ≤25; ⚠️ need-based — $100k+ income may not \"demonstrate need\"", "kind": ""},
  {"id": "H05", "name": "HACU partner scholarships", "tier": "H", "amount": "$1,500–$10,000", "deadline": {"raw": "opens ~Feb 2027", "recurring": false, "fuzzy": true}, "effort": "per award", "status": "todo", "recurring": false, "url": "https://hacu.net/programs/hacu-scholarship-program/", "notes": "⚠️ most require enrollment at a HACU-member institution — UA almost certainly NOT one; verify before applying", "kind": ""},
  {"id": "H06", "name": "UA Multicultural Center (inquiry)", "tier": "H", "amount": "discretionary? — ask", "deadline": {"raw": "no deadline", "recurring": false, "fuzzy": true}, "effort": "email/call (15 min)", "status": "todo", "recurring": false, "url": "https://multicultural.uark.edu", "notes": "No scholarship currently listed — email uamc@uark.edu + scholars@uark.edu to ask about Latino-specific funds", "kind": ""},
  {"id": "H07", "name": "APIA Scholars (Asian & Pacific Islander American Scholarship Fund)", "tier": "H", "amount": "$2,500–$20,000 (one-time to multi-year)", "deadline": {"raw": "next cycle ~Nov 2026 – Jan 2027 (2026-27 ran Nov 15–Jan 15; confirm)", "recurring": false, "fuzzy": true}, "effort": "application + 250–500-word essay", "status": "todo", "recurring": false, "url": "https://apiascholars.org/scholarships/", "notes": "US citizen/PR (or COFA nationals); enrolling US college fall 2027; no income cap; first-gen NOT required; heritage: verify on scholarships page (FAQ says all ethnicities welcome)", "kind": ""},
  {"id": "H08", "name": "KASF (Korean-American Scholarship Foundation)", "tier": "H", "amount": "$500–$5,000", "deadline": {"raw": "region-specific — apply to AR's region (confirm)", "recurring": false, "fuzzy": true}, "effort": "essay + recs + financial need", "status": "todo", "recurring": false, "url": "https://kasf.org/scholarships/", "notes": "Korean heritage (any citizenship incl. Korean nationals); GPA 3.0+; full-time enrollment; KASF-KIA bonus: 3.5 GPA + STEM/business major, possibly larger award + video testimonial", "kind": ""},
  {"id": "H09", "name": "HHF Youth Awards (Hispanic Heritage Foundation)", "tier": "H", "amount": "up to $4,000", "deadline": {"raw": "Nov 1, 2026", "recurring": false, "fuzzy": false}, "effort": "online app + essays", "status": "todo", "recurring": false, "url": "https://hispanicheritage.org", "notes": "Hispanic/Latino HS senior; GPA 3.0+; Engineering & Technology category fits CS; no income cap, no first-gen req; strong fit for LULAC VP + service — verify category list", "kind": ""},
  {"id": "H10", "name": "ScholarSHPE (SHPE)", "tier": "H", "amount": "$1,000–$10,000", "deadline": {"raw": "opens ~Feb 2027", "recurring": false, "fuzzy": true}, "effort": "app + essays/recs", "status": "todo", "recurring": false, "url": "https://shpe.org", "notes": "join SHPE now; STEM major; GPA 2.5+; some sponsor awards need US citizenship", "kind": ""},
  {"id": "H11", "name": "GMiS Scholars (Great Minds in STEM)", "tier": "H", "amount": "$500–$5,000", "deadline": {"raw": "opens ~Mar 2027", "recurring": false, "fuzzy": true}, "effort": "750–850 word essay + 2 recs", "status": "todo", "recurring": false, "url": "https://greatmindsinstem.org", "notes": "STEM; GPA 3.0+; leadership/service emphasized; open to all STEM not just Hispanic", "kind": ""},
  {"id": "H12", "name": "One Korean Foundation / AR Korean Chamber", "tier": "H", "amount": "~$1,000", "deadline": {"raw": "Dec (annual)", "recurring": false, "fuzzy": true}, "effort": "essay", "status": "todo", "recurring": false, "url": "", "notes": "Korean-American Arkansas students; confirm 2027 via AR Korean Chamber", "kind": ""},
  {"id": "I01", "name": "Fisher House — Scholarships for Military Children", "tier": "I", "amount": "$2,000 (min 1 per commissary)", "deadline": {"raw": "Dec 10, 2026 – Feb 11, 2027", "recurring": false, "fuzzy": false}, "effort": "application + essay + transcript", "status": "todo", "recurring": false, "url": "https://militaryscholar.org", "notes": "Children of active, reserve, or retired military — Max qualifies via dad; $35M+ awarded, 14,000+ recipients", "kind": ""},
  {"id": "I02", "name": "AUSA scholarships", "tier": "I", "amount": "$2,000–$25,000 (Vuono $10k · Cribbins STEM $10k · Chabraja STEM $5k · MilDef $5k · Van Autreve $2k–$25k)", "deadline": {"raw": "Feb 20 – May 7 (2026 cycle; 2027 likely similar)", "recurring": false, "fuzzy": true}, "effort": "1-page autobiography + career letter + 2 recs (+ transcript for STEM)", "status": "todo", "recurring": false, "url": "https://ausa.org/scholarships", "notes": "AUSA Premium membership required (dad can join; covers his children); single application covers all awards", "kind": ""},
  {"id": "I03", "name": "Army Scholarship Foundation", "tier": "I", "amount": "varies (needs confirmation)", "deadline": {"raw": "spring (confirm)", "recurring": false, "fuzzy": true}, "effort": "application", "status": "todo", "recurring": false, "url": "https://armyscholarshipfoundation.org", "notes": "Sons/daughters of US Army soldiers (incl. active duty); site unreachable at research time — verify", "kind": ""},
  {"id": "I04", "name": "ThanksUSA", "tier": "I", "amount": "varies (needs confirmation)", "deadline": {"raw": "~Jan–Feb 2027 (confirm)", "recurring": false, "fuzzy": true}, "effort": "application", "status": "todo", "recurring": false, "url": "https://thanksusa.org/scholarships/", "notes": "Spouses + children of active-duty troops; referenced by AUSA; site fetch failed — verify", "kind": ""},
  {"id": "I05", "name": "Folds of Honor / Heroes' Legacy", "tier": "I", "amount": "$2,000–$5,000", "deadline": {"raw": "varies", "recurring": false, "fuzzy": true}, "effort": "—", "status": "skipped", "recurring": false, "url": "https://foldsofhonor.org", "notes": "Only children of fallen or disabled service members — N/A unless dad has a disability rating", "kind": ""},
  {"id": "I06", "name": "Operation Homefront — Military Child of the Year (Army)", "tier": "I", "amount": "$10,000", "deadline": {"raw": "nomination closes Dec 1, 2026", "recurring": false, "fuzzy": false}, "effort": "nomination + recs", "status": "todo", "recurring": false, "url": "https://operationhomefront.org", "notes": "ages 13–18; legal dependent of active-duty (DEERS); Army category; not need-based — verify birthday", "kind": ""},
  {"id": "I07", "name": "VFW Voice of Democracy", "tier": "I", "amount": "$35,000 national / $1,000+ state", "deadline": {"raw": "Oct 31, 2026", "recurring": false, "fuzzy": false}, "effort": "3–5 min audio essay", "status": "todo", "recurring": false, "url": "https://vfw.org", "notes": "open to all HS grades 9–12; US citizen/PR; not military-exclusive", "kind": ""},
  {"id": "I08", "name": "MOAA Education Assistance Program", "tier": "I", "amount": "interest-free loans + grants", "deadline": {"raw": "~Nov 1–Mar 1", "recurring": false, "fuzzy": true}, "effort": "one app + essays", "status": "todo", "recurring": false, "url": "https://moaa.org", "notes": "child of officer OR active/retired enlisted; GPA 3.0+; if dad is an OFFICER needs paid MOAA membership — confirm dad's rank", "kind": ""},
  {"id": "I09", "name": "AER — MG James Ursano Scholarship", "tier": "I", "amount": "varies (need-based)", "deadline": {"raw": "opens Jan 1, closes Apr 1", "recurring": false, "fuzzy": true}, "effort": "app + FAFSA", "status": "todo", "recurring": false, "url": "https://armyemergencyrelief.org", "notes": "child of active-duty Army, under 24; need-based via FAFSA — low yield at >$100k income", "kind": ""}
];

const FILLKIT = {
  "profile": [
    [
      "Full name",
      "Max B. Hill De Santiago"
    ],
    [
      "Email",
      "Max.Hill037@gmail.com"
    ],
    [
      "Phone",
      "479-507-5373"
    ],
    [
      "City / State",
      "Rogers, AR"
    ],
    [
      "High school",
      "Rogers High School, Class of 2027"
    ],
    [
      "GPA",
      "3.85 / 4.0"
    ],
    [
      "Intended college",
      "University of Arkansas, Fayetteville (Fall 2027)"
    ],
    [
      "Intended major",
      "Computer Science / Cybersecurity / Engineering + Business (confirm exact combination)"
    ],
    [
      "Heritage",
      "Mexican-American and Korean-American"
    ],
    [
      "First-generation college student?",
      "No"
    ],
    [
      "Citizenship",
      "US citizen"
    ],
    [
      "Military family",
      "Father: U.S. Army, active duty (deployed in Germany); parents divorced"
    ],
    [
      "Languages",
      "English; intermediate Spanish"
    ],
    [
      "Certifications",
      "Cybersecurity certification [CERT NAME]; First Aid"
    ],
    [
      "Licenses",
      "Licensed driver"
    ]
  ],
  "contact": [
    [
      "full name",
      "Max B. Hill De Santiago"
    ],
    [
      "email",
      "Max.Hill037@gmail.com"
    ],
    [
      "phone",
      "479-507-5373"
    ],
    [
      "high school",
      "Rogers High School, Class of 2027"
    ],
    [
      "city / state",
      "Rogers, AR"
    ]
  ],
  "bios": [
    {
      "label": "~30 words",
      "text": "Senior at Rogers High School (GPA 3.85) with a technical focus in robotics and cybersecurity. Founded a 25-client lawn-care business, and leads youth civic programs serving 150+ students across Northwest Arkansas."
    },
    {
      "label": "~60 words",
      "text": "Rogers High School senior (GPA 3.85) with a technical focus in robotics and cybersecurity. Founded Max Mows at 15 and scaled it to 25 residential clients. As a youth council president and LULAC officer, he has led 150+ students through civic projects — including 30+ beds built for families in need and 100+ hours of tornado-relief service. Also a varsity tennis and track athlete whose portrait photograph was exhibited at Crystal Bridges Museum."
    },
    {
      "label": "~120 words",
      "text": "Max B. Hill De Santiago is a Rogers High School senior (Class of 2027, GPA 3.85) planning to study computer science and business at the University of Arkansas. He brings a builder's mindset: in TSA Robotics he engineered and programmed a robot from scratch, and a cybersecurity certification taught him how systems are attacked and defended. He founded Max Mows at 15, growing a lawn-care business to 25 clients. As Vice President of the LULAC Youth Council, he forged a partnership with Sleep in Heavenly Peace that delivered 30+ beds to low-income families, mobilized a 15-student team for tornado relief, and ran a community food-security drive. He is also President of the Youth Area Council, a varsity tennis and track athlete, and a photographer whose work was exhibited at Crystal Bridges Museum of American Art."
    }
  ],
  "awards": [
    "Straight A Honor Roll Award, Rogers Chamber of Commerce (May 2026)",
    "Volunteer of the Year, Rogers Chamber of Commerce (May 2025)",
    "BYU Tennis Championship — Division Winner (July 2025)",
    "Whitey Smith Relay Carnival — 2nd Place, 4x200 Relay (April 2026)",
    "Crystal Bridges Museum of American Art — portrait photograph selected for exhibition (elite intensive program)"
  ],
  "activities": [
    {
      "role": "President",
      "org": "Youth Area Council",
      "detail": "Preside over monthly strategic planning; lead workshops for 150+ youth on teamwork and mentorship"
    },
    {
      "role": "Vice President",
      "org": "LULAC Youth Council",
      "detail": "Led Sleep in Heavenly Peace bed build (30+ beds); tornado relief 100+ hrs, 20 properties; food-security drive"
    },
    {
      "role": "Member",
      "org": "TSA Robotics",
      "detail": "Built and programmed competition robot from scratch; debugged hardware and software to improve performance"
    },
    {
      "role": "Founder",
      "org": "Max Mows (lawn care)",
      "detail": "Founded and scaled business to 25 residential clients; handled marketing, scheduling, and quality control"
    },
    {
      "role": "Varsity",
      "org": "Rogers High School Tennis",
      "detail": "Varsity player; BYU division winner; balanced tournament calendar with academics and internship"
    },
    {
      "role": "Varsity",
      "org": "Rogers High School Track & Field",
      "detail": "100m and 200m sprinter; 2nd place 4x200 at Whitey Smith Relay Carnival"
    },
    {
      "role": "Intern",
      "org": "Ozark Trade & Holdings",
      "detail": "Supply-chain logistics and asset deployment; managed financial accounts/billing in Excel; supported office systems"
    }
  ],
  "essays": [
    {
      "id": "about",
      "title": "Tell us about yourself",
      "words": 250,
      "text": "My senior year looks different than I planned. In May I started a logistics internship, in August I took over a youth council presidency, and in between I kept practice, robotics, and my lawn-care company running. I like it that way.\n\nI've always been the kind of student who builds things. In TSA Robotics I engineered a robot from scratch and spent hours troubleshooting a misreading sensor or a stalled servo. That patience carried into code — Python, Java, and a cybersecurity certification that taught me how attackers think and how to defend against them. I want to build a career protecting the systems people rely on.\n\nBut technology isn't the whole story. In 2024 I founded Max Mows and grew it to 25 clients, learning scheduling, marketing, and how to keep a promise. As Vice President of the LULAC Youth Council, I helped organize a bed build that delivered 30+ beds to families across Northwest Arkansas, mobilized 15 students for tornado relief that cleared 20 properties, and led a food drive for local food banks. As President of the Youth Area Council, I run workshops for 150+ students on teamwork and mentorship.\n\nI also play varsity tennis and run the 100m and 200m, where I learned that improvement comes from showing up consistently. When I'm not in motion, I take portraits — one was exhibited at Crystal Bridges.\n\nI'm ready to bring the same energy to college."
    },
    {
      "id": "leadership",
      "title": "Leadership",
      "words": 250,
      "text": "Two titles on my résumé taught me what leadership actually is. As President of the Youth Area Council and Vice President of the LULAC Youth Council, I learned that leading means organizing people around a result — not just holding the title.\n\nAs Youth Area Council President, I run monthly strategic planning and lead workshops for 150+ youth participants on teamwork and professional mentorship. The work taught me to build an agenda, delegate, and keep a roomful of teenagers engaged, which is its own skill.\n\nThe LULAC Youth Council is where I learned to turn plans into impact. I forged a partnership with Sleep in Heavenly Peace, coordinating volunteers to manufacture and distribute 30+ beds for low-income households across Northwest Arkansas. When tornadoes hit our region, I mobilized a 15-student rapid response team that contributed 100+ hours clearing debris from 20 residential properties. Later, I ran a community food-security drive, using peer outreach to bring in substantial donations for local food banks.\n\nWhat I'm most proud of isn't the numbers. Every project started with someone who had a need and a small team that wanted to help. My job was to make the path clear — who brings the wood, who drives the truck, who calls the family. Leadership, I've learned, is mostly logistics with a sense of purpose."
    },
    {
      "id": "community",
      "title": "Community impact",
      "words": 250,
      "text": "In April of my junior year, tornadoes tore through our region. Within days, I had mobilized 15 students from the LULAC Youth Council into a rapid response team. Over the following weeks we contributed 100+ hours clearing debris from 20 residential properties — hauling branches, sorting salvage, and showing up at houses where people simply needed another set of hands.\n\nThat experience shaped how I think about service. Help is most useful when it's organized, so I started looking for ways to make our council's impact systematic. I forged a partnership with Sleep in Heavenly Peace, and together we manufactured and distributed 30+ beds to low-income households across Northwest Arkansas. A bed might not sound like much, but for a kid who has been sleeping on a floor, it's a home.\n\nI've also run a community food-security drive, using peer outreach to rally donations for local food banks, and as Youth Area Council President I lead workshops where 150+ students learn teamwork and mentorship skills — so the next generation of volunteers is better prepared than I was.\n\nWhat drives me is simple: I've seen what a small, organized team can do for a neighborhood, and I want to keep building those teams. College is the next step in learning how to organize at a bigger scale — and in the meantime, I'll keep showing up with the trailer and the chainsaw."
    },
    {
      "id": "challenge",
      "title": "A challenge I overcame",
      "words": 250,
      "text": "In my first year of TSA Robotics, I decided to build the robot from scratch. I had no kit, no mentor with the answers — just a chassis, some motors, and a determination to make it work.\n\nEverything that could go wrong did. The motors wouldn't spin consistently, the code compiled but the robot ignored it, and the chassis fell apart at our first practice match. It would have been easier to use a prebuilt kit, but I had committed to the harder path, so I learned to debug systematically: isolate one variable, test it, write down what happened, move to the next. I read the datasheets. I rewrote the code. I replaced the wiring. And eventually — after more late nights than I care to count — the robot did what I told it to.\n\nWhat I kept from that project wasn't the robot. It was the method: break the problem down, test one thing at a time, and don't quit because it's hard. That method carried into my cybersecurity coursework, where I learned to trace how an attack happens step by step, and into my lawn-care business, where a broken mower or a no-show client is just another problem to isolate and solve.\n\nI still get excited about hard problems. I just know better now: hard is where the good stuff is, and patience usually beats brilliance."
    },
    {
      "id": "career",
      "title": "Career goals",
      "words": 250,
      "text": "I want to build a career in cybersecurity — specifically, protecting the systems that small businesses and communities depend on.\n\nThe interest started with curiosity and turned into training. In TSA Robotics I learned to build and break systems from the hardware up, and my cybersecurity certification taught me how networks are attacked and defended. I learned Python and Java, and a logistics internship showed me how real organizations depend on data they can't afford to lose. Every week I saw how much of our region's commerce runs through spreadsheets, payment systems, and client records — and how fragile that trust is.\n\nMy community service points the same direction. In the LULAC Youth Council I organized teams to build beds, clear storm debris, and feed neighbors, and I learned that the most vulnerable people are the ones least equipped to protect themselves. That's true of technology too: small businesses and families can't afford enterprise security teams, so they're the ones most likely to get hurt.\n\nAt the University of Arkansas I plan to combine computer science and engineering with business — building secure systems and learning to run them. After college, I want to come back to Northwest Arkansas and work where I grew up — helping the businesses and organizations here stay safe as they grow.\n\nThe technical skills matter. But the reason I want them is to be useful to people, the same reason I loaded a chainsaw into the truck after the tornadoes."
    },
    {
      "id": "why-ua",
      "title": "Why the University of Arkansas?",
      "words": 200,
      "text": "The University of Arkansas is where I want to earn my degree, and not just because it's forty minutes from home.\n\nAcademically, it's the right fit. I want to study computer science and engineering with a business focus — the College of Engineering and Walton College are exactly the combination I need [CONFIRM/ADD specific program or professor]. My GPA, robotics background, and cybersecurity certification put me in a position to make the most of it — and to keep raising the bar, because the Honors College is a goal I'm working toward.\n\nBut the strongest reason is the community. I've spent high school leading youth councils, organizing tornado relief, and building beds for families in Northwest Arkansas. Staying in-state means I can keep serving that community while I learn — interning, mentoring younger students, and giving back to the place that raised me.\n\nIt also makes financial sense for our family. Between in-state tuition, the merit scholarships UA offers through its single freshman application, and the state scholarships I'll apply for through SAMS, an Arkansas education is one we can afford without taking on crushing debt.\n\nI want to be a Razorback — to earn my degree at home, serve at home, and build my career at home."
    },
    {
      "id": "heritage",
      "title": "Heritage & identity",
      "words": 250,
      "text": "I carry two cultures: my Mexican heritage from my mother's side and my Korean heritage from my father's. My dad is a soldier currently serving overseas in Germany, and my mom raised me as a single parent — she worked to give me a future her own family couldn't have imagined. Both sides taught me that community is everything.\n\nMy Mexican-American identity is part of why I serve. When I joined the LULAC Youth Council, I didn't just join a club — I found a tradition of civic organizing that goes back generations, and I worked to earn my place in it. As Vice President, I helped lead a bed build for families in need, mobilized students after the tornadoes, and organized a food drive. I've seen what our community can do when it works together, and I want to be part of that story.\n\nMy Korean heritage taught me the same lesson from a different angle: respect for elders, the value of hard work, and the importance of showing up for family — blood or chosen. [ADD any personal detail, e.g., food, language, relatives.]\n\nGrowing up in a single-parent household, I learned early that nobody was coming to do the work for us. I started a lawn-care business at 15. I took on leadership roles. I kept my grades up.\n\nThis scholarship matters to me because it would let me focus on engineering and service instead of tuition — and because I believe in paying forward what my community gave me. My mom worked so I could have choices. I want to use them well."
    },
    {
      "id": "entrepreneurship",
      "title": "Entrepreneurship — Max Mows",
      "words": 150,
      "text": "In the summer before my freshman year, I wanted money and I wanted to learn how money worked. So I started mowing lawns.\n\nMax Mows grew from a single mower into a real business with 25 residential clients. I learned to market — flyers first, then word of mouth and referrals — and to schedule like a professional, because in lawn care, reliability is the product. When a mower broke, I fixed it or worked around it. When a client wasn't happy, I fixed that too.\n\nThe business taught me things no classroom could: pricing, cash flow, client communication, and the discipline of showing up in the summer heat. I kept it running through August 2026, even while I added an internship, robotics, and varsity athletics to my schedule.\n\nI'm proud of Max Mows because it was mine — founded, run, and grown by me. It proved I can build something from nothing and manage it well. College is the next business, and I'm ready to put the same work in."
    }
  ],
  "oneliners": [
    {
      "label": "Career goal",
      "text": "To build a career in cybersecurity, protecting the systems that small businesses and communities depend on."
    },
    {
      "label": "Leadership, one sentence",
      "text": "I lead by organizing people around a clear result — 150 students in a workshop, or 15 volunteers clearing storm debris."
    },
    {
      "label": "Biggest achievement",
      "text": "Building a competition robot from scratch, then debugging it until it worked."
    },
    {
      "label": "Community service, one sentence",
      "text": "I serve because I've seen what a small, organized team can do for a neighborhood."
    },
    {
      "label": "Why do you deserve this scholarship?",
      "text": "I've earned my place through work — a business I built, a community I've served, and grades I've maintained — and this scholarship would let me focus on engineering instead of tuition."
    },
    {
      "label": "What makes you unique?",
      "text": "I'm a robotics builder and a portrait photographer, a track sprinter and a youth council president — and I bring the same stubborn patience to everything."
    },
    {
      "label": "Describe a time you showed leadership",
      "text": "When tornadoes hit our region, I mobilized 15 students and cleared 20 properties in over 100 hours of service."
    },
    {
      "label": "Hobbies/interests",
      "text": "Photography (my portrait was exhibited at Crystal Bridges), sprinting, robotics, and building things."
    }
  ]
};
